app/routes.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_user, login_required, logout_user
import app
from flask import Blueprint, render_template
from app import db, login_manager
from app.models import User, Note, Client, UserIP
from app.forms import RegistrationForm, LoginForm, NoteForm, PasswordForm, OTPForm
from bleach import clean
from sqlalchemy import or_
from cryptography.fernet import Fernet
import hashlib
import base64
import time
from datetime import datetime
import pyotp
from flask import session
import sys

# Create a TOTP (Time-based One-Time Password) instance
totp = pyotp.TOTP(pyotp.random_base32(), interval=60)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    session['two_step_authenticated'] = False
    if current_user.is_authenticated:
        user_notes = db.session.query(Note, User).filter(or_(Note.user_id == current_user.id, Note.public == True)).join(User).all()
    else:
        user_notes = db.session.query(Note, User).filter(Note.public == True).join(User).all()

    return render_template('index.html', notes=user_notes)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)

        try:
            user.set_password(form.password.data)

            ip_address = request.remote_addr
            user_ip = UserIP(ip_address=ip_address, user=user, is_associated=True)
            
            db.session.add_all([user, user_ip])
            db.session.commit()
            flash('Your account has been created!', 'success')
            return redirect(url_for('main.login'))
        except ValueError as e:
            flash(str(e), 'danger')
    else:
        if form.errors.items():
            flash('Account creation failed, check your inputs and try again.', 'danger')

    return render_template('register.html', form=form)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    client = Client.query.filter_by(ip=request.remote_addr).first()
    if client is None:
        client = Client(ip=request.remote_addr, failed_login_requests=0, last_request_date=datetime.utcnow())
        db.session.add(client)
        db.session.commit()

    delay_seconds = 1
    form = LoginForm()
    elapsed_time = datetime.utcnow() - client.last_request_date

    if client.failed_login_requests >= 10 and elapsed_time.total_seconds() < 3600:
        flash('Too many login attempts, wait an hour', 'danger')
        return redirect(url_for('main.index'))
    else:
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and user.check_password(form.password.data):
                session['two_step_authenticated'] = True
                session['user_email'] = form.email.data
                return redirect(url_for('main.provide_otp'))
                
            else:
                flash('Login unsuccessful. Please check email and password.', 'danger')
                time.sleep(delay_seconds)
                client.failed_login_requests +=1
            db.session.commit()
        else:
            if form.errors.items():
                flash('Login unsuccessful. Please check email and password.', 'danger')
                time.sleep(delay_seconds)
    return render_template('login.html', form=form)

@bp.route('/provide-otp', methods=['GET', 'POST'])
def provide_otp():
    # o1 = generate_otp(totp)
    # sys.stdout.write("token 1")
    o2 = generate_otp(totp)
    sys.stdout.write("o2")
    # sys.stdout.flush()
    if 'two_step_authenticated' not in session or not session['two_step_authenticated']:
        return redirect(url_for('main.index'))

    form = OTPForm()



    if form.validate_on_submit():
        user_entered_otp = form.otp.data
        generated_otp = generate_otp(totp)

        # Validate the entered OTP
        if user_entered_otp == generated_otp:  # Replace 'generated_otp' with the actual OTP
            # Clear the session variable
            session.pop('two_step_authenticated', None)
            user_email = session.get('user_email', None)
            user = User.query.filter_by(email=user_email).first()
            client = Client.query.filter_by(ip=request.remote_addr).first()
            # Log the user in
            login_user(user)
            client.failed_login_requests = 0
            db.session.commit()
            login_ip = request.remote_addr
            associated_ips = [ip.ip_address for ip in user.ips if ip.is_associated]
            not_associated_ips = [ip.ip_address for ip in user.ips if not ip.is_associated]

            if login_ip not in associated_ips:
                new_user_ip = UserIP(ip_address=login_ip, user=user, is_associated=False)
                db.session.add(new_user_ip)
                db.session.commit()
            elif not not_associated_ips is None:
                flash('There were new devices that logged into your account', 'danger')
                return render_template('new_ips.html', ips=not_associated_ips)

            flash('Logged in!', 'success')
            return redirect(url_for('main.index'))

        flash('Invalid OTP. Please try again.', 'danger')

    return render_template('provide_otp.html', form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out', 'success')
    return redirect(url_for('main.index'))

@bp.route('/note/new', methods=['GET', 'POST'])
@login_required
def new_note():
    form = NoteForm()
    if form.is_submitted():
        form.validate()  # Explicitly validate the form
    if form.validate_on_submit():
        content = sanitize_content(form.content.data)
        if(form.encrypted.data):
            if(form.password.data):
                key = base64.urlsafe_b64encode(hashlib.sha256(form.password.data.encode()).digest())
                content=Fernet(key).encrypt(content.encode('utf-8'))
            else:
                flash('Encrypted note must have a password', 'danger')
                return render_template('new_note.html', form=form,)

        note = Note(content=content, encrypted=form.encrypted.data, public=form.public.data, user_id=current_user.id)
        db.session.add(note)
        db.session.commit()
        flash('Your note has been created!', 'success')
        return redirect(url_for('main.index'))
    
    return render_template('new_note.html', form=form,)

@bp.route('/decrypt_note/<int:note_id>', methods=['GET', 'POST'])
def decrypt_note(note_id):
    note = Note.query.get_or_404(note_id)
    user = User.query.get_or_404(note.user_id)

    if note.public or not current_user.is_anonymous and current_user.id == note.user_id :

        password_form = PasswordForm()

        if password_form.validate_on_submit():
            try:
                key = base64.urlsafe_b64encode(hashlib.sha256(password_form.password.data.encode()).digest())
                note.content = Fernet(key).decrypt(note.content).decode('utf-8')
                return render_template('decrypted_note.html', note=note, user=user)
            except Exception as e:
                flash("Invalid password. Please try again.", 'danger')

        return render_template('password_form.html', form=password_form, note=note)
    else:
        flash("You don't have permission to decrypt this note.", 'danger')
        return redirect(url_for('main.index'))

def sanitize_content(content):
    allowed_tags = ['h1', 'h2', 'h3', 'h4', 'h5', 'strong', 'a', 'img', 'i']
    allowed_attributes = {'a': ['href', 'title'],'img': ['src', 'alt']}
    
    cleaned_content = clean(content, tags=allowed_tags, attributes=allowed_attributes)
    return cleaned_content

def generate_otp(totp):

    # Generate and print the OTP
    otp = totp.now()
    print(f"Generated OTP: {otp}")
    sys.stdout.write("token: "+otp)
    sys.stdout.flush()

    return otp

app/templates/decrypted_note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Decrypted Note</title>
</head>
<body>
    <h1>Decrypted Note</h1>

    <div>
        <p>{{ note.content | safe }}</p>
        <p><small>Posted by: {{ user.username }} on {{ note.timestamp.strftime('%Y-%m-%d %H:%M:%S') }}</small></p>
    </div>

    <a href="{{ url_for('main.index') }}">Back to Notes</a>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Welcome to notes sharing app</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'success' %}
                    <p style="color:green">{{ message }}</p>
                {% elif category == 'danger' %}
                    <p style="color:red">{{ message }}</p>
                {% else %}
                    <p>{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% if current_user.is_authenticated %}
        <p>Hello, {{ current_user.username }}!</p>
        <a href="{{ url_for('main.logout') }}">Logout</a>
    {% else %}
        <a href="{{ url_for('main.login') }}">Login</a>
        <a href="{{ url_for('main.register') }}">Register</a>
    {% endif %}
    <hr>
    {% for note, user in notes %}
    <div>
        {% if note.encrypted %}
            <p>Encrypted Content</p>
            <a href="{{ url_for('main.decrypt_note', note_id=note.id) }}">Decrypt Note</a>
        {% else %}
            <p>{{ note.content | safe}}</p>
        {% endif %}
        <p><small>Posted by: {{ user.username }} on {{ note.timestamp.strftime('%Y-%m-%d %H:%M:%S') }}</small></p>
    </div>
    <hr>
    {% endfor %}
    {% if current_user.is_authenticated %}
        <a href="{{ url_for('main.new_note') }}">Add a New Note</a>
    {% endif %}
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'success' %}
                    <p style="color:green">{{ message }}</p>
                {% elif category == 'danger' %}
                    <p style="color:red">{{ message }}</p>
                {% else %}
                    <p>{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <form method="post" action="{{ url_for('main.login') }}">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <label for="email">Email:</label>
        {{ form.email }}
        <br>
        <label for="password">Password:</label>
        {{ form.password }}
        <br>
        <input type="submit" value="Login">
    </form>
    <p>Don't have an account? <a href="{{ url_for('main.register') }}">Register</a></p>
</body>
</html>

app/templates/new_ips.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1  style="color:red">Someone logged in from other device(s)</h1>
    <hr>
    {% for ip in ips %}
    <div>
        <p>{{ ip }}</p>
    </div>
    <hr>
    {% endfor %}
    <a href="{{ url_for('main.index') }}">Back to Notes</a>
</body>
</html>

app/templates/new_note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Note</title>
</head>
<body>
    <h1>Create a New Note</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'success' %}
                    <p style="color:green">{{ message }}</p>
                {% elif category == 'danger' %}
                    <p style="color:red">{{ message }}</p>
                {% else %}
                    <p>{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('main.new_note') }}">
        {{ form.csrf_token }}

        <label for="content">Note Content:</label>
        {{ form.content }}

        <label for="encrypted">Encrypted:</label>
        {{ form.encrypted }}

        <label for="password">Note password:</label>
        {{ form.password }}

        <label for="public">Should be public:</label>
        {{ form.public }}
        
        <button type="submit">Save Note</button>
    </form>
    <br>
    <h2>aviable html markups</h2>
    <p>
    # Bold: &lt;strong>text&lt;/strong>
    <br>
    # Italic: &lt;i>text&lt;/i>
    <br>
    # Header: &lt;h{1-5}> text&lt;/h{1-5}>
    <br>
    # Link: &lt;a src="URL">text&lt;/a>
    <br>
    # Image: &lt;img alt="alt text" src="image URL">
    </p>
    <br>
    <a href="{{ url_for('main.index') }}">Back to Notes</a>
</body>
</html>

app/templates/password_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Entry</title>
</head>
<body>
    <h1>Enter Password</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'success' %}
                    <p style="color:green">{{ message }}</p>
                {% elif category == 'danger' %}
                    <p style="color:red">{{ message }}</p>
                {% else %}
                    <p>{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('main.decrypt_note', note_id=note.id) }}">
        {{ form.csrf_token }}

        <label for="password">Password:</label>
        {{ form.password }}
        {{ form.submit }}
    </form>

    <a href="{{ url_for('main.index') }}">Cancel</a>
</body>
</html>

app/templates/provide_otp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Entry</title>
</head>
<body>
    <div>
        <h2>Provide OTP</h2>
        <p>Enter the OTP sent to your device.</p>

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <form method="post" action="{{ url_for('main.provide_otp') }}">
            {{ form.csrf_token }}

            <label for="otp">OTP:</label>
            <input type="text" id="otp" name="otp" required>

            <button type="submit">Submit OTP</button>
        </form>
    </div>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'success' %}
                    <p style="color:green">{{ message }}</p>
                {% elif category == 'danger' %}
                    <p style="color:red">{{ message }}</p>
                {% else %}
                    <p>{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% if form.errors %}
            {% for field, errors in form.errors.items() %}
                {% for error in errors %}
                <p style="color:red">{{ error }}</p>
                {% endfor %}
            {% endfor %}
    {% endif %}
    <form method="post" action="{{ url_for('main.register') }}">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <label for="username">Username:</label>
        {{ form.username }}
        <br>
        <label for="email">Email:</label>
        {{ form.email }}
        <br>
        <label for="password">Password:</label>
        {{ form.password }}
        <br>
        <label for="confirm_password">Confirm Password:</label>
        {{ form.confirm_password }}
        <br>
        <input type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{{ url_for('main.login') }}">Login</a></p>
</body>
</html>